DOWNLOAD_DIR = r"DIRECTORY TO DOWNLOAD TO"

SPOTIFY_CLIENT_ID = "YOUR SPOTIFY DEV CLIENT ID"
SPOTIFY_CLIENT_SECRET = "SECRET ID"
SPOTIFY_REDIRECT_URI = "http://127.0.0.1:8888/callback" #DO NOT USE LOCALHOST, DEPRECATED
SPOTIFY_PLAYLIST_ID = "PLAYLIST ID"

LOG_FILE = "downloaded_songs.txt"
